CREATE TABLE [dbo].[AUD_PROCEDURE](
	dt_fecha SMALLDATETIME NOT NULL,
	st_database NVARCHAR(256) NOT NULL,
	st_evento NVARCHAR(100) NOT NULL,
	st_objeto NVARCHAR(256) NOT NULL,
	st_comando NVARCHAR(MAX) NOT NULL,
	st_usuario NVARCHAR(100) NOT NULL
)

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[AUD_PROCEDURE] ADD  CONSTRAINT [DF__AUD_PROCEDURE_USUARIO]  DEFAULT SUBSTRING(system_user, PATINDEX('%\%', system_user)+1, len(system_user)-PATINDEX('%\%', system_user)) FOR [st_usuario]
GO

ALTER TABLE [dbo].[AUD_PROCEDURE] ADD  CONSTRAINT [DF__AUD_PROCEDURE_FECHA_MOD]  DEFAULT CAST(GETDATE() AS SMALLDATETIME)  FOR [dt_fecha]

GO
